name: Build and deploy Python app to Azure Web App - chatbot-backend-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip backend folder for deployment
        run: |
          cd ..
          zip -r release.zip backend -x "backend/venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip
    deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d app

      - name: Debug: List files after unzip
        run: ls -R app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D1F0536D1E954B3FAA381FE21DAA5CD4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_89B213987FE0459E9A32543A42BBB9DF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CC6D5394CB8D4068817F2655DBE292A5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chatbot-backend-app'
          slot-name: 'Production'
          package: app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d app
        
      - name: Debug: List files after unzip
        run: ls -R app
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D1F0536D1E954B3FAA381FE21DAA5CD4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_89B213987FE0459E9A32543A42BBB9DF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CC6D5394CB8D4068817F2655DBE292A5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chatbot-backend-app'
          slot-name: 'Production'
          package: app
